swagger: '2.0'
info:
  version: 0.0.1
  title: Henohenoapi
  description: >-
    The project aims to create a platform for managing exams, teachers can
    public exams(which have a deadline) and add tasks to them, while students
    can submit their answers and answer.
#dominio e baseroot
host: henoheno-app.herokuapp.com
basePath: /
#portocollo supportato
schemes:
  - http
#formati dati accettabile da server
consumes:
  - application/json
#formati dati prodotto da server
produces:
  - application/json
tags:
  - name: Users_resource
    description: Operations regarding the users
  - name: Exams_resource
    description: Operations regarding the exam
  - name: Tasks_resource
    description: Operations regarding the tasks
  - name: Answer_resource
    description: Operations regarding the answer
  - name: Groups_resource
    description: Operations regarding the students
  - name: Marks_resource
    description: Operations regarding the marks
  - name: Review_resource
    description: Operations regarding the reviews
#parte di url--------------------------------------------------------------------------
paths:
  /auth:
    post:
      summary: user authentication
      tags:
        - Users_resource
      responses:
        '201':
          description: Created
          
  /users:
    get:
      summary: users list
      tags:
        - Users_resource
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
          examples:
            application/json:
              - user_id: 1
                user_name: mario2018
              - user_id: 2
                user_name: luca2019
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    post:
      summary: user subscription
      tags:
        - Users_resource
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  '/users/{user_id}':
    get:
      summary: access one specific user
      tags:
        - Users_resource
      parameters:
        - $ref: '#/parameters/User_id_in_path'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
          examples:
            application/json:
              user_id: 1
              user_name: mario2018
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
  '/users/{user_id}/exams':
    get:
      summary: get the exams assigned to a student
      tags:
        - Users_resource
      parameters:
        - $ref: '#/parameters/User_id_in_path'
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  '/users/{user_id}/marks':
    get:
      summary: get the marks assigned to a student
      tags:
        - Users_resource
      parameters:
        - $ref: '#/parameters/User_id_in_path'
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          
  /exams:
    get:
      summary: exams list
      tags:
        - Exams_resource
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Exam'
          examples:
            application/json:
              - exam_id: 1
                exam_name: analisi1
                author_id: 7
              - exam_id: 2
                exam_name: analisi2
                author_id: 8
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    post:
      summary: create an exam by defining a set of tasks and other stuff
      tags:
        - Exams_resource
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  '/exams/{exam_id}':
    get:
      summary: access one specific exam
      tags:
        - Exams_resource
      parameters:
        - $ref: '#/parameters/Exam_id_in_path'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Exam'
          examples:
            application/json:
              exam_id: 1
              exam_name: analisi1
              author_id: 7
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    put:
      summary: update an exam by adding groups or changing specific fields
      tags:
        - Exams_resource
      parameters:
        - $ref: '#/parameters/Exam_id_in_path'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '204':
          description: No Content
        '404':
          description: Not Found
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
  '/exams/{exam_id}/answer':
    get:
      summary: access the answer of a specific exam
      tags:
        - Exams_resource
      parameters:
        - $ref: '#/parameters/Exam_id_in_path'
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
  '/exams/{exam_id}/tasks':
    get:
      summary: access the tasks of a specific exam
      tags:
        - Exams_resource
      parameters:
        - $ref: '#/parameters/Exam_id_in_path'
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
          
  /tasks:
    get:
      summary: tasks list
      tags:
        - Tasks_resource
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
          examples:
            application/json:
              - task_id: 88
                task_name: es 6
              - task_id: 89
                task_name: es 5
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    post:
      summary: create new task
      tags:
        - Tasks_resource
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  '/tasks/{task_id}':
    get:
      summary: access one specific task
      tags:
        - Tasks_resource
      parameters:
        - $ref: '#/parameters/Task_id_in_path'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Task'
          examples:
            application/json:
              task_id: 88
              task_name: es 6
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    put:
      summary: update an existing task
      tags:
        - Tasks_resource
      parameters:
        - $ref: '#/parameters/Task_id_in_path'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '204':
          description: No Content
        '404':
          description: Not Found
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
    delete:
      summary: delete an existing task
      tags:
        - Tasks_resource
      parameters:
        - $ref: '#/parameters/Task_id_in_path'
      responses:
        '204':
          description: correctly deleted
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
          
  /answer:
    get:
      summary: Answer list
      tags:
        - Answer_resource
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Answer'
          examples:
            application/json:
              - solution_id: 44
                task_id: 88
                author_id: 1
              - solution_id: 45
                task_id: 89
                author_id: 1
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    post:
      summary: submit new answer
      tags:
        - Answer_resource
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  '/answer/{answer_id}':
    get:
      summary: access a specific answer
      tags:
        - Answer_resource
      parameters:
        - $ref: '#/parameters/Answer_id_in_path'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Answer'
          examples:
            application/json:
              solution_id: 44
              task_id: 88
              author_id: 1
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    put:
      summary: update an existing solution
      tags:
        - Answer_resource
      parameters:
        - $ref: '#/parameters/Answer_id_in_path'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '204':
          description: No Content
        '404':
          description: Not Found
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
  '/answer/{answer_id}/reviews':
    get:
      summary: access the reviews of a solution
      tags:
        - Answer_resource
      parameters:
        - $ref: '#/parameters/Answer_id_in_path'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Review'
          examples:
            application/json:
              solution_id: 44
              task_id: 88
              author_id: 1
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    post:
      summary: submit a review to an answer
      tags:
        - Answer_resource
      parameters:
        - $ref: '#/parameters/Answer_id_in_path'
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
  /groups:
    get:
      summary: groups list
      tags:
        - Groups_resource
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Group'
          examples:
            application/json:
              - group_id: 88
                group_name: henohenomoheji
                group_members: [9, 91, 19]
              - group_id: 89
                group_name: apicoltori
                group_members: [9, 91, 19]
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    post:
      summary: create new group
      tags:
        - Groups_resource
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  '/groups/{group_id}':
    get:
      summary: see the members of a group
      tags:
        - Groups_resource
      parameters:
        - $ref: '#/parameters/Group_id_in_path'
      responses:
        '200':
          description: positive answer
          schema:
            type: array
            items:
              $ref: '#/definitions/Group'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    put:
      summary: update an existing group
      tags:
        - Groups_resource
      parameters:
        - $ref: '#/parameters/Group_id_in_path'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '204':
          description: No Content
        '404':
          description: Not Found
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
          
  /marks:
    get:
      summary: marks list
      tags:
        - Marks_resource
      responses:
        '200':
          description: positive answer
          schema:
            type: array
            items:
              $ref: '#/definitions/Mark'
          examples:
            application/json:
              - mark_id: 88
                student_id: 100
                teache_id: 23
              - group_id: 89
                group_name: 99
                group_members: 12
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
    post:
      summary: add new mark
      tags:
        - Marks_resource
      responses:
        '201':
          description: Created
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
  /reviews:
    get:
      summary: reviews list
      tags:
        - Reviews_resource
      responses:
        '200':
          description: positive answer
          schema:
            type: array
            items:
              $ref: '#/definitions/Review'
          examples:
            application/json:
              - task_id: 88
                student_id: 100
                solution_id: 23
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
  '/reviews/{review_id}':
    get:
      summary: read a specific review
      tags:
        - Reviews_resource
      parameters:
        - $ref: '#/parameters/Review_id_in_path'
      responses:
        '200':
          description: positive answer
          schema:
            type: array
            items:
              $ref: '#/definitions/Review'
          examples:
            application/json:
              - task_id: 88
                student_id: 100
                solution_id: 23
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        default:
          $ref: '#/responses/Unknown_error'
          
#parte di costante --------------------------------------------------------------------------
definitions:
  Error:
    properties:
      code:
        type: string
      message:
        type: string
  #oggetto utente
  User:
    #tipo di dati
    type: object
    #proprietà
    properties:
      user_id:
        type: integer
      user_name:
        type: string
    #proprietà obbligatorie 
    required:
      - user_id
  Exam:
    type: object
    properties:
      exam_id:
        type: integer
      exam_name:
        type: string
      task_set:
        type: array
        items:
          type: integer #has to be of Tasks
      author_id:
        type: integer
    required:
      - exam_id
  Task:
    type: object
    properties:
      task_id:
        type: integer
      task_name:
        type: string
    required:
      - task_id
  Answer:
    type: object
    properties:
      aswer_id:
        type: integer
      task_id:
        type: integer
      author_id:
        type: integer
    required:
      - solution_id
  Group:
    type: object
    properties:
      group_id:
        type: integer
      group_name:
        type: string
      group_members:
        type: array
        items:
          type: integer
    required:
      - group_id
  Mark:
    type: object
    properties:
      mark_id:
        type: integer
      student_id:
        type: integer
      teacher_id:
        type: integer
    required:
      - mark_id
  Review:
    type: object
    properties:
      review_id:
        type: integer
      student_id:
        type: integer
      task_id:
        type: integer
    required:
      - review_id
parameters:
  User_id_in_path:
    name: user_id
    description: id utente
    in: path
    type: integer
    required: true
  Exam_id_in_path:
    name: exam_id
    description: id esame
    in: path
    type: integer
    required: true
  Task_id_in_path:
    name: task_id
    description: id task
    in: path
    type: integer
    required: true
  Answer_id_in_path:
    name: answer_id
    description: answer id
    in: path
    type: integer
    required: true
  Group_id_in_path:
    name: group_id
    description: the id of a group
    in: path
    type: integer
    required: true
  Mark_id_in_path:
    name: mark_id
    description: the id of a mark
    in: path
    type: integer
    required: true
  Review_id_in_path:
    name: review_id
    description: the id of the review
    in: path
    type: integer
    required: true
responses:
  Unknown_error:
    description: unhandled error
    schema:
      $ref: '#/definitions/Error'